if(NOT DEFINED PACKAGE_DIRECTORY)
  message(FATAL_ERROR "PACKAGE_DIRECTORY is required")
endif()

if(WIN32)
  set(archive_pattern "*.zip")
else()
  set(archive_pattern "*.tar.gz")
endif()
file(GLOB archives LIST_DIRECTORIES false "${PACKAGE_DIRECTORY}/${archive_pattern}")
list(LENGTH archives archive_count)
if(NOT archive_count EQUAL 1)
  message(FATAL_ERROR "Expected one package archive, found ${archive_count}: ${archives}")
endif()

list(GET archives 0 archive)
set(extract_directory "${PACKAGE_DIRECTORY}/smoke")
file(REMOVE_RECURSE "${extract_directory}")
file(MAKE_DIRECTORY "${extract_directory}")
file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${extract_directory}")

set(packaged_license "${extract_directory}/LICENSE")
if(NOT EXISTS "${packaged_license}" OR IS_DIRECTORY "${packaged_license}")
  message(FATAL_ERROR "Package does not contain a LICENSE file")
endif()
file(SHA256 "${packaged_license}" packaged_license_hash)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../LICENSE" source_license_hash)
if(NOT packaged_license_hash STREQUAL source_license_hash)
  message(FATAL_ERROR "Packaged LICENSE does not match the source LICENSE")
endif()

set(EXECUTABLE "${extract_directory}/bin/cpp-release-lab")
if(WIN32)
  string(APPEND EXECUTABLE ".exe")
endif()
set(EXPECTED_EXIT 0)
set(EXPECTED_STDOUT "Hello, World!\n")
include("${CMAKE_CURRENT_LIST_DIR}/CheckCli.cmake")
